#!/usr/bin/env tsx
/**
 * Wrap compiled worker code as a string constant
 *
 * Reads the compiled run-worker.js and embeds it as a string constant.
 * This prevents webpack from processing it as a worker.
 */

// eslint-disable-next-line fast-import/no-restricted-imports
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const WORKER_FILE = resolve(__dirname, "../../dist/codeRuntime/run-worker.js");
const OUTPUT_FILE = resolve(
  __dirname,
  "../../dist/codeRuntime/worker-code.generated.js"
);
const OUTPUT_DTS_FILE = resolve(
  __dirname,
  "../../dist/codeRuntime/worker-code.generated.d.ts"
);

try {
  console.log("Wrapping worker code...");

  // Read the compiled worker code
  const workerCode = readFileSync(WORKER_FILE, "utf-8");

  // Generate JavaScript module with embedded worker code
  const generatedContent = `// Auto-generated by src/codeRuntime/wrap-worker.ts
// DO NOT EDIT - changes will be overwritten on next build

/**
 * Compiled worker code embedded as a string.
 * Used to create a Blob URL at runtime, bypassing webpack's worker processing.
 */
export const WORKER_CODE = ${JSON.stringify(workerCode)};
`;

  writeFileSync(OUTPUT_FILE, generatedContent, "utf-8");

  // Generate TypeScript declaration file
  const dtsContent = `// Auto-generated by src/codeRuntime/wrap-worker.ts
// DO NOT EDIT - changes will be overwritten on next build

export declare const WORKER_CODE: string;
`;
  writeFileSync(OUTPUT_DTS_FILE, dtsContent, "utf-8");

  const sizeKB = (workerCode.length / 1024).toFixed(2);
  console.log(`Worker wrapped successfully (${sizeKB} KB)`);
  console.log(`   Output: ${OUTPUT_FILE}`);
} catch (error) {
  console.error("Failed to wrap worker:");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
