// DO NOT EDIT THIS FILE. It is auto-generated by the generate-ambient script.

import type { ConnectingCell } from "../components/expandable/connectingCell/connectingCell.ts";
import type { ExpandableCell } from "../components/expandable/expandableCell/expandableCell.ts";
import type { ExpandableCellIcon } from "../components/expandable/expandableCellIcon/expandableCellIcon.ts";
import type { Pill } from "../components/pill/pill.ts";
import type { ReactCustomElement } from "./components.ts";

declare global {
  // eslint-disable-next-line @typescript-eslint/consistent-type-definitions
  interface HTMLElementTagNameMap {
    "spk-connecting-cell": ConnectingCell;
    "spk-expandable-cell": ExpandableCell;
    "spk-expandable-cell-icon": ExpandableCellIcon;
    "spk-pill": Pill;
  }
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/consistent-type-definitions
    interface IntrinsicElements {
      "spk-connecting-cell": ReactCustomElement<ConnectingCell>;
      "spk-expandable-cell": ReactCustomElement<ExpandableCell>;
      "spk-expandable-cell-icon": ReactCustomElement<ExpandableCellIcon>;
      "spk-pill": ReactCustomElement<Pill>;
    }
  }
}
