// DO NOT EDIT THIS FILE. It is auto-generated by the generate-ambient script.
/* eslint-disable @typescript-eslint/consistent-type-definitions, @typescript-eslint/no-namespace */

import type { ExpandableBreakout } from "../components/expandable/expandableBreakout/component.ts";
import type { ExpandableProperty } from "../components/expandable/expandableProperty/component.ts";
import type { ConnectingCell } from "../components/expandable/internal/connectingCell/component.ts";
import type { ExpandableCell } from "../components/expandable/internal/expandableCell/component.ts";
import type { ExpandableCellIcon } from "../components/expandable/internal/expandableCellIcon/component.ts";
import type { NonExpandableCell } from "../components/expandable/internal/nonExpandableCell/component.ts";
import type { TreeTopper } from "../components/expandable/internal/treeTopper/component.ts";
import type { Pill } from "../components/pill/pill.ts";
import type { ReactCustomElement } from "./components.ts";

declare global {
  interface HTMLElementTagNameMap {
    "spk-expandable-breakout": ExpandableBreakout;
    "spk-expandable-property": ExpandableProperty;
    "spk-internal-connecting-cell": ConnectingCell;
    "spk-internal-expandable-cell": ExpandableCell;
    "spk-internal-expandable-cell-icon": ExpandableCellIcon;
    "spk-internal-non-expandable-cell": NonExpandableCell;
    "spk-internal-tree-topper": TreeTopper;
    "spk-pill": Pill;
  }
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "spk-expandable-breakout": ReactCustomElement<ExpandableBreakout>;
      "spk-expandable-property": ReactCustomElement<ExpandableProperty>;
      "spk-internal-connecting-cell": ReactCustomElement<ConnectingCell>;
      "spk-internal-expandable-cell": ReactCustomElement<ExpandableCell>;
      "spk-internal-expandable-cell-icon": ReactCustomElement<ExpandableCellIcon>;
      "spk-internal-non-expandable-cell": ReactCustomElement<NonExpandableCell>;
      "spk-internal-tree-topper": ReactCustomElement<TreeTopper>;
      "spk-pill": ReactCustomElement<Pill>;
    }
  }
}
